# Use the official Grafana image as the base
FROM grafana/grafana

# Expose Grafana port
EXPOSE 3000

# Copy custom Grafana configuration files if needed
# COPY custom.ini /etc/grafana/custom.ini

# Command to run Grafana
CMD ["--config=/etc/grafana/grafana.ini"]
